# Generated by Django 4.2 on 2023-05-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_rename_description_libro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.FileField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
