# Generated by Django 4.2 on 2023-05-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_rename_imagen_libro_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='file',
            new_name='archivo',
        ),
    ]
