# Generated by Django 4.2 on 2023-05-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_rename_file_libro_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='titulo',
        ),
        migrations.AddField(
            model_name='libro',
            name='destino',
            field=models.TextField(null=True, verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='libro',
            name='f_emision',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='f_envio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='oficio',
            field=models.TextField(null=True, verbose_name='Oficio'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='archivo',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
