# Generated by Django 4.2 on 2023-05-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_alter_libro_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='f_emision',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
