# Generated by Django 4.2 on 2023-05-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_alter_libro_f_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='f_emision',
            field=models.DateField(null=True),
        ),
    ]
