# Generated by Django 4.2 on 2023-05-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_alter_libro_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='destino',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May')], default='APR', max_length=15),
        ),
    ]
