# Generated by Django 4.2 on 2023-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_alter_libro_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('oficio', models.TextField(null=True, verbose_name='Oficio')),
                ('oficina_emi', models.CharField(max_length=100, null=True, verbose_name='Oficina Emisora')),
                ('f_recep', models.DateField(null=True)),
                ('archivo', models.FileField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
            ],
        ),
    ]
