# Generated by Django 4.2 on 2023-05-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_libro2'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro2',
            name='marcado',
            field=models.BooleanField(default=False, verbose_name='Marcado'),
        ),
    ]
