# Generated by Django 4.2 on 2023-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0019_alter_libro_archivo_alter_libro_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='libro2',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='libro2',
            name='f_recep',
            field=models.DateField(null=True, verbose_name='Fecha de recepción'),
        ),
        migrations.AlterField(
            model_name='libro2',
            name='marcado',
            field=models.BooleanField(default=False, verbose_name='¿Respondido?'),
        ),
    ]
