# Generated by Django 4.2 on 2023-05-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0020_alter_libro_archivo_alter_libro2_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('oficina_dest', models.CharField(max_length=100, null=True, verbose_name='Oficina Destino')),
                ('f_emision', models.DateField(null=True, verbose_name='Fecha de emisión')),
                ('archivo', models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo')),
            ],
        ),
        migrations.CreateModel(
            name='Libro4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('oficina_emi', models.CharField(max_length=100, null=True, verbose_name='Oficina Emisora')),
                ('f_recep', models.DateField(null=True, verbose_name='Fecha de recepción')),
                ('archivo', models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo')),
            ],
        ),
        migrations.CreateModel(
            name='Libro5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('personal', models.CharField(max_length=100, null=True, verbose_name='Oficina Emisora')),
                ('dias_rest', models.IntegerField(null=True, verbose_name='Vacaciones restantes')),
                ('f_recep', models.DateField(null=True, verbose_name='Fecha de recepción')),
                ('archivo', models.FileField(null=True, upload_to='archivos/', verbose_name='Archivo')),
            ],
        ),
    ]
