# Generated by Django 4.2 on 2023-05-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0022_alter_libro5_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro6',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_apellidos', models.CharField(max_length=100, null=True, verbose_name='Personal')),
                ('dias_rest', models.IntegerField(null=True, verbose_name='Vacaciones restantes')),
            ],
        ),
        migrations.RemoveField(
            model_name='libro5',
            name='personal',
        ),
        migrations.AddField(
            model_name='libro5',
            name='libro6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.libro6', verbose_name='Libro 6'),
        ),
    ]
