# Generated by Django 4.2 on 2023-05-29 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0024_remove_libro5_dias_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro5',
            name='libro6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.libro6', to_field='nombres_apellidos', verbose_name='Libro 6'),
        ),
        migrations.AlterField(
            model_name='libro6',
            name='nombres_apellidos',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Personal'),
        ),
    ]
