# Generated by Django 4.2 on 2023-05-29 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0025_alter_libro5_libro6_alter_libro6_nombres_apellidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro5',
            name='libro6',
        ),
        migrations.AddField(
            model_name='libro5',
            name='nombres_apellidos',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.libro6'),
        ),
    ]
