# Generated by Django 4.2.1 on 2023-05-30 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0026_remove_libro5_libro6_libro5_nombres_apellidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro5',
            name='nombres_apellidos',
        ),
    ]
