# Generated by Django 4.2.1 on 2023-05-30 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0027_remove_libro5_nombres_apellidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro6',
            name='nombres_apellidos',
        ),
        migrations.AddField(
            model_name='libro5',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.libro6'),
        ),
        migrations.AddField(
            model_name='libro6',
            name='apellido_materno',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Personal'),
        ),
        migrations.AddField(
            model_name='libro6',
            name='apellido_paterno',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Personal'),
        ),
        migrations.AddField(
            model_name='libro6',
            name='nombres',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Personal'),
        ),
    ]
