# Generated by Django 4.2 on 2023-05-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0028_remove_libro6_nombres_apellidos_libro5_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro6',
            name='apellido_materno',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='libro6',
            name='apellido_paterno',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='libro6',
            name='nombres',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nombres'),
        ),
    ]
