# Generated by Django 4.2 on 2023-05-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0029_alter_libro6_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro6',
            name='condicion',
            field=models.CharField(choices=[('1', 'Nombrado'), ('2', 'Contratado'), ('3', 'CAS')], default='2', max_length=1),
        ),
    ]
