# Generated by Django 4.2 on 2023-05-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0030_libro6_condicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro6',
            name='dias_rest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vacaciones restantes'),
        ),
    ]
