# Generated by Django 4.2 on 2023-05-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0031_alter_libro6_dias_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='libro2',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='libro3',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='libro4',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Archivo'),
        ),
    ]
