# Generated by Django 4.2 on 2023-05-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0032_alter_libro_archivo_alter_libro2_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro6',
            name='condicion',
            field=models.CharField(choices=[('1', 'Nombrado'), ('2', 'Contratado'), ('3', 'CAS')], default='1', max_length=1),
        ),
    ]
