# Generated by Django 4.2 on 2023-05-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0033_alter_libro6_condicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro6',
            name='apellido_materno',
            field=models.CharField(max_length=30, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='libro6',
            name='apellido_paterno',
            field=models.CharField(max_length=30, null=True, verbose_name='Apellido Paterno'),
        ),
    ]
